# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ea43777aa6f8844cd7dbf639324b8a6f1b1f9ea09c7be242214e800f667771c854375a2c700ce599e15e5226a69f5996147b1382b05b6e55ad91c6f85881d731

test:
  secret_key_base: 9a9c2531c92ac3fe7752f5fb79e8e5b0875e319b20b2ca0efa9c8e5db16a4fe783d8ee907d1bcca75ab5d0f29ce7e4839f889b3a4ccd441fa5aeb49a028e4256

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
