PersonalPronoun.find_or_create_by(ru_who: 'они', ru_whom: 'их', en_who: 'they', en_whom: 'them')
PersonalPronoun.find_or_create_by(ru_who: 'они', ru_whom: 'им', en_who: 'they', en_whom: 'them')
PersonalPronoun.find_or_create_by(ru_who: 'мы', ru_whom: 'нам', en_who: 'we', en_whom: 'us')
PersonalPronoun.find_or_create_by(ru_who: 'она', ru_whom: 'ей', en_who: 'she', en_whom: 'her')
PersonalPronoun.find_or_create_by(ru_who: 'он', ru_whom: 'ему', en_who: 'he', en_whom: 'him')
PersonalPronoun.find_or_create_by(ru_who: 'вы', ru_whom: 'вам', en_who: 'you', en_whom: 'you')
PersonalPronoun.find_or_create_by(ru_who: 'ты', ru_whom: 'тебе', en_who: 'you', en_whom: 'you')
PersonalPronoun.find_or_create_by(ru_who: 'он', ru_whom: 'его', en_who: 'he', en_whom: 'him')
PersonalPronoun.find_or_create_by(ru_who: 'она', ru_whom: 'её', en_who: 'she', en_whom: 'her')
PersonalPronoun.find_or_create_by(ru_who: 'мы', ru_whom: 'нас', en_who: 'we', en_whom: 'us')
PersonalPronoun.find_or_create_by(ru_who: 'ты', ru_whom: 'тебя', en_who: 'you', en_whom: 'you')
PersonalPronoun.find_or_create_by(ru_who: 'вы', ru_whom: 'вас', en_who: 'you', en_whom: 'you')
PersonalPronoun.find_or_create_by(ru_who: 'я', ru_whom: 'меня', en_who: 'i', en_whom: 'me')
PersonalPronoun.find_or_create_by(ru_who: 'я', ru_whom: 'мне', en_who: 'i', en_whom: 'me')

PersonalPronoun.find_or_create_by(ru_who: 'они', ru_whom: 'к ним', en_who: 'they', en_whom: 'to them')
PersonalPronoun.find_or_create_by(ru_who: 'они', ru_whom: 'от ниx', en_who: 'they', en_whom: 'from them')
PersonalPronoun.find_or_create_by(ru_who: 'мы', ru_whom: 'к нам', en_who: 'we', en_whom: 'to us')
PersonalPronoun.find_or_create_by(ru_who: 'мы', ru_whom: 'от нас', en_who: 'we', en_whom: 'from us')
PersonalPronoun.find_or_create_by(ru_who: 'она', ru_whom: 'к ней', en_who: 'she', en_whom: 'to her')
PersonalPronoun.find_or_create_by(ru_who: 'она', ru_whom: 'от неё', en_who: 'she', en_whom: 'from her')
PersonalPronoun.find_or_create_by(ru_who: 'он', ru_whom: 'к нему', en_who: 'he', en_whom: 'to him')
PersonalPronoun.find_or_create_by(ru_who: 'он', ru_whom: 'от него', en_who: 'he', en_whom: 'from him')
PersonalPronoun.find_or_create_by(ru_who: 'вы', ru_whom: 'к вам', en_who: 'you', en_whom: 'to you')
PersonalPronoun.find_or_create_by(ru_who: 'вы', ru_whom: 'от ваc', en_who: 'you', en_whom: 'from you')
PersonalPronoun.find_or_create_by(ru_who: 'ты', ru_whom: 'к тебе', en_who: 'you', en_whom: 'to you')
PersonalPronoun.find_or_create_by(ru_who: 'ты', ru_whom: 'от тебя', en_who: 'you', en_whom: 'from you')
PersonalPronoun.find_or_create_by(ru_who: 'я', ru_whom: 'ко мне', en_who: 'i', en_whom: 'to me')
PersonalPronoun.find_or_create_by(ru_who: 'я', ru_whom: 'от меня', en_who: 'i', en_whom: 'from me')

Place.find_or_create_by(pretext_en: 'in', pretext_ru: 'в', name_ru: 'в городе', name_en: 'the city')
Place.find_or_create_by(pretext_en: 'in', pretext_ru: 'в', name_ru: 'в деревне', name_en: 'the village')
Place.find_or_create_by(pretext_en: 'from', pretext_ru: 'из', name_ru: 'из деревни', name_en: 'the village')
Place.find_or_create_by(pretext_en: 'to', pretext_ru: 'в(к)', name_ru: 'в деревню', name_en: 'the village')
Place.find_or_create_by(pretext_en: 'to', pretext_ru: 'в(к)', name_ru: 'в город', name_en: 'the city')
Place.find_or_create_by(pretext_en: 'from', pretext_ru: 'из', name_ru: 'из города', name_en: 'the city')
Place.find_or_create_by(pretext_en: 'in', pretext_ru: 'в', name_ru: 'в России', name_en: 'Russia')
Place.find_or_create_by(pretext_en: 'from', pretext_ru: 'из', name_ru: 'из России', name_en: 'Russia')
Place.find_or_create_by(pretext_en: 'to', pretext_ru: 'в(к)', name_ru: 'в Россию', name_en: 'Russia')
Place.find_or_create_by(pretext_en: 'in', pretext_ru: 'в', name_ru: 'в магазине', name_en: 'market')
Place.find_or_create_by(pretext_en: 'from', pretext_ru: 'из', name_ru: 'из магазина', name_en: 'market')
Place.find_or_create_by(pretext_en: 'to', pretext_ru: 'в(к)', name_ru: 'в магазин', name_en: 'market')
Place.find_or_create_by(pretext_en: 'in', pretext_ru: 'в', name_ru: 'в офисе', name_en: 'office')
Place.find_or_create_by(pretext_en: 'from', pretext_ru: 'из', name_ru: 'из офиса', name_en: 'office')
Place.find_or_create_by(pretext_en: 'to', pretext_ru: 'в(к)', name_ru: 'в офис', name_en: 'office')

Interrogative.find_or_create_by(ru: 'Что', en: 'What')
Interrogative.find_or_create_by(ru: 'Какой', en: 'What')
Interrogative.find_or_create_by(ru: 'Кто', en: 'Who')
Interrogative.find_or_create_by(ru: 'Где', en: 'Where')
Interrogative.find_or_create_by(ru: 'Куда', en: 'Where')
Interrogative.find_or_create_by(ru: 'Когда', en: 'When')
Interrogative.find_or_create_by(ru: 'Зачем', en: 'Why')
Interrogative.find_or_create_by(ru: 'Почему', en: 'Why')
Interrogative.find_or_create_by(ru: 'Как', en: 'How')
